// app/services/services.ts
export const services = [
  {
    id: "ultrasonic-scaling",
    title: "Ultrasonic Scaling with Deep Cleaning",
    description: "Removes plaque and tartar using ultrasonic vibrations, ensuring optimal oral hygiene.",
    details: "Ultrasonic scaling utilizes high-frequency vibrations to effectively remove plaque and tartar buildup from teeth surfaces and below the gumline. This advanced technique ensures a thorough cleaning, promoting optimal oral hygiene and preventing periodontal diseases.",
    imageUrl: "/images/ultrasonic_scaling.jpg",
  },
  {
    id: "teeth-whitening",
    title: "Polishing and Teeth Whitening Therapy",
    description: "Brighten your smile with professional polishing and whitening treatments.",
    details: "Our teeth whitening therapy uses safe and effective bleaching agents to lighten stains caused by food, drinks, and aging. Combined with polishing, it ensures a smooth and bright surface.",
    imageUrl: "/images/teeth_whitening.jpg",
  },
  {
    id: "fluoride-therapy",
    title: "Fluoride Therapy",
    description: "Strengthens tooth enamel and prevents decay with targeted fluoride applications.",
    details: "Fluoride therapy involves the application of fluoride to the teeth to strengthen enamel and prevent decay. This treatment is especially beneficial for children and individuals at higher risk of cavities.",
    imageUrl: "/images/fluoride_therapy.jpg",
  },
  {
    id: "composite-filling",
    title: "Light Cure Composite Filling",
    description: "Restores cavities with durable, tooth-colored composite materials for a seamless appearance.",
    details: "Composite fillings are used to repair decayed, chipped, or fractured teeth. The tooth-colored resin material blends seamlessly with natural teeth, providing both durability and aesthetics.",
    imageUrl: "/images/composite_filling.jpg",
  },
  {
    id: "root-canal",
    title: "Root Canal Treatment",
    description: "Saves infected or damaged teeth by cleaning and sealing the root canals.",
    details: "Root canal treatment involves removing infected or inflamed pulp from the tooth's interior, cleaning and disinfecting the canals, and then filling and sealing them to preserve the tooth structure.",
    imageUrl: "/images/root_canal.jpg",
  },
  {
    id: "tooth-extraction",
    title: "Tooth Extraction",
    description: "Safely removes damaged or problematic teeth to maintain overall oral health.",
    details: "Tooth extraction is performed when a tooth is severely damaged or decayed beyond repair. The procedure ensures the removal of the problematic tooth to prevent further oral health issues.",
    imageUrl: "/images/tooth_extraction.jpg",
  },
  {
    id: "pulpectomy",
    title: "Pulpectomy",
    description: "A pediatric procedure to remove infected pulp from primary teeth, preserving tooth structure.",
    details: "Pulpectomy involves removing the diseased pulp tissue from a child's primary tooth, cleaning and disinfecting the canals, and then filling them to maintain the tooth's function until it naturally falls out.",
    imageUrl: "/images/pulpectomy.png",
  },
  {
    id: "complete-denture",
    title: "Complete Denture",
    description: "Custom-made removable appliances to replace all missing teeth in an arch.",
    details: "Complete dentures are full-arch prosthetic devices designed to replace all missing teeth in the upper or lower jaw, restoring function and aesthetics for individuals who have lost multiple teeth.",
    imageUrl: "/images/complete_denture.webp",
  },
  {
    id: "partial-denture",
    title: "Partial Denture",
    description: "Removable appliances designed to replace one or more missing teeth, restoring function and aesthetics.",
    details: "Partial dentures are used when some natural teeth remain. They consist of replacement teeth attached to a gum-colored base, often connected by metal frameworks that hold the denture in place.",
    imageUrl: "/images/partial_denture.jpg",
  },
  {
    id: "zirconia-crown",
    title: "Zirconia Crown",
    description: "Durable and aesthetic tooth-colored crowns made from zirconia material.",
    details: "Zirconia crowns are known for their strength and natural appearance. Made from zirconium dioxide, they are highly resistant to chipping and cracking, making them ideal for restoring both front and back teeth.",
    imageUrl: "/images/zirconia_crown.jpg",
  },
  {
    id: "porcelain-crown",
    title: "Porcelain Crown",
    description: "Natural-looking crowns crafted from porcelain to restore tooth shape and function.",
    details: "Porcelain crowns are custom-made caps that cover damaged or decayed teeth. They mimic the translucency and color of natural teeth, providing an aesthetically pleasing restoration.",
    imageUrl: "/images/porcelain_crown.jpeg",
  },
  {
    id: "metallic-crown",
    title: "Metallic Crown",
    description: "Strong and long-lasting crowns made from metal alloys, ideal for molars.",
    details: "Metallic crowns, often made from gold or other metal alloys, are highly durable and resistant to wear. They are especially suitable for molars, where the forces from chewing are greatest.",
    imageUrl: "/images/metallic_crown.jpeg",
  },
  {
    id: "orthodontic-appliance",
    title: "Orthodontic Appliance for Aesthetic Treatment",
    description: "Devices designed to correct teeth alignment and improve smile aesthetics.",
    details: "Orthodontic appliances, such as braces or clear aligners, are used to straighten misaligned teeth, correct bite issues, and enhance overall dental aesthetics.",
    imageUrl: "/images/orthodontic_appliance.jpg",
  },
];
